# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"whoami": "00_core.ipynb",
         "GuessWho": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://bsalanie.github.io/nbdev_one/"

git_url = "https://github.com/bsalanie/nbdev_one/tree/master/"

def custom_doc_links(name): return None
