# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['whoami', 'GuessWho']

# Cell
def whoami(name: str="Bernard"):
    """
    tells you who you are

    @param str name: your name

    @return nothing
    """
    print(f"You must be {name}.")

# Cell
class GuessWho:
    "a guessing interface"
    def __init__(self, name="Bernard"):
        self.name = name

    def guess(self):
        "tells the user their name"
        return whoami(self.name)

